default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: 'password'
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: radar_development

test:
  <<: *default
  database: radar_test

production:
  url: <%= ENV['DATABASE_URL'] %>
